version: '2'
services:
  db1:
    image: mysql:5.7
    ports:
      - 3356:3306
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/db1/conf.d:/etc/mysql/conf.d
  db2:
    image: mysql:5.7
    ports:
      - 3357:3306
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/db2/conf.d:/etc/mysql/conf.d
  web:
    build: .
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    depends_on:
      - db1
      - db2
    volumes:
      - .:/akane