# db1
db1_default: &db1_default
  adapter: mysql2
  encoding: utf8
  pool: 5

db1_production: &db1_production
  <<: *db1_default
  host: db1
  database: db1_production
  username: <%= ENV['DB1_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DB1_PRODUCTION_PASSWORD'] %>

db1_development: &db1_development
  <<: *db1_default
  host: db1
  database: db1_development
  username: <%= ENV['DB1_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['DB1_DEVELOPMENT_PASSWORD'] %>

db1_test: &db1_test
  <<: *db1_default
  host: db1
  database: db1_test
  username: <%= ENV['DB1_TEST_USERNAME'] %>
  password: <%= ENV['DB1_TEST_PASSWORD'] %>

# db2
db2_default: &db2_default
  adapter: mysql2
  encoding: utf8
  pool: 5

db2_production: &db2_production
  <<: *db2_default
  host: db2
  database: db2_production
  username: <%= ENV['DB2_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DB2_PRODUCTION_PASSWORD'] %>

db2_development: &db2_development
  <<: *db2_default
  host: db2
  database: db2_development
  username: <%= ENV['DB2_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['DB2_DEVELOPMENT_PASSWORD'] %>

db2_test: &db2_test
  <<: *db2_default
  host: db2
  database: db2_test
  username: <%= ENV['DB2_TEST_USERNAME'] %>
  password: <%= ENV['DB2_TEST_PASSWORD'] %>

# default
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: db2

development:
  <<: *db1_development

test:
  <<: *db1_test

production:
  <<: *default
  database: akane_production
  username: akane
  password: <
